### ISSUE TITLE
Code obfuscated?

### ISSUE THREAD

**Issue by jkoenig134** [coltonj96/ParticleAnimationApi#1]
Hey dude, nice Plugin. But is your code obfuscated or why do you use variable names like a and b?

**Comment by coltonj96** [comment]
Thanks for the compliment. The variables are usually set to private and thus does not need to be named to describe what they hold.

**Comment by coltonj96** [comment]
The "obfuscated" variables when assigned, tell you what they are

**Comment by jkoenig134** [comment]
Allright. Its just better to understand your code, when they are named like that.
Tanks for you fast answer!
